Added tighter dependency on Highline as their later release broke things
rake db:bootstrap would fail using e.g. highline 1.6.5 with the error:

undefined method `parse' for String:Class
/Library/Ruby/Gems/1.8/gems/highline-1.6.5/lib/highline/question.rb:329:in `convert'
/Library/Ruby/Gems/1.8/gems/highline-1.6.5/lib/highline.rb:253:in `ask'
…/radiant/lib/radiant/setup.rb:92:in `prompt_for_admin_name'
…/radiant/lib/radiant/setup.rb:29:in `create_admin_user'
…/radiant/lib/radiant/setup.rb:19:in `bootstrap'
…/radiant/lib/radiant/setup.rb:10:in `bootstrap'
…/radiant/lib/tasks/database.rake:43
[…]